### ISSUE TITLE
Cannot access newly added 'Metodiky' and 'REFLEXE'

### ISSUE THREAD

**Issue by samotion2** [vanetnuggets/vanetlab-web#3]
You don't know what files are currently selected, please add color to differenciate between them.
![image](https://user-images.githubusercontent.com/56072273/198015538-8bc8bc95-55ef-4143-8bd0-41252d1a745f.png)
After you click on metodika you get this error.
![image](https://user-images.githubusercontent.com/56072273/198015370-4214d0cf-dd98-466b-8a05-0b48d6d1fda6.png)

**Comment by omartinka** [comment]
issue cannot be replicated, marked as closed.
