### ISSUE TITLE
dates in zoznam sprintov are not displayed correctly

### ISSUE THREAD

**Issue by samotion2** [vanetnuggets/vanetlab-web#4]
![image](https://user-images.githubusercontent.com/56072273/203526687-1992b492-1ba2-4209-850b-d0ae855fba72.png)
issue in druhy sprint and only present in mobile layout
resolution 720x842

**Comment by fud4ly** [comment]
asi fixed
![obrázok](https://user-images.githubusercontent.com/47903327/203540131-a1f2fd3f-9243-484f-941b-79ef556a3e6c.png)
